<a href="https://colab.research.google.com/github/kimheeseo/2022_AI_SW_Programmingstudy/blob/main/practice_logistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# read data from file
df = pd.read_csv('data06_iris2.csv')

In [3]:
X = df.iloc[:,:-1]
Y = df['Species']

# **train & test data**

In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size=0.4,random_state=1) 

In [5]:
xtrain.shape

(60, 4)

# **logistic regression**

In [6]:
from sklearn.linear_model import LogisticRegression
# multiple logistic regression
f = LogisticRegression()
f.fit(xtrain,ytrain)

LogisticRegression()

In [7]:
yhat_train = f.predict(xtrain)

In [8]:
yhat_train

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [9]:
ytrain #label자체를 예측하는 것.

86    1
53    1
77    1
15    0
83    1
41    0
45    0
91    1
26    0
98    1
43    0
55    1
24    0
4     0
58    1
49    0
21    0
87    1
3     0
74    1
30    0
66    1
70    1
42    0
47    0
89    1
8     0
60    1
0     0
90    1
57    1
22    0
61    1
63    1
7     0
96    1
13    0
68    1
85    1
14    0
29    0
28    0
11    0
18    0
20    0
50    1
25    0
6     0
71    1
76    1
1     0
16    0
64    1
79    1
5     0
75    1
9     0
72    1
12    0
37    0
Name: Species, dtype: int64

In [10]:
yhat_train_prob = f.predict_proba(xtrain) #확률값 예측

In [11]:
yhat_train_prob #각각의 값은 확률값을 나타내기에 0~1의 값을 가진다.

array([[0.13829219, 0.86170781],
       [0.30135055, 0.69864945],
       [0.51581254, 0.48418746],
       [0.57350307, 0.42649693],
       [0.33849752, 0.66150248],
       [0.74800742, 0.25199258],
       [0.89217947, 0.10782053],
       [0.50839028, 0.49160972],
       [0.78208815, 0.21791185],
       [0.16746581, 0.83253419],
       [0.99811241, 0.00188759],
       [0.00134489, 0.99865511],
       [0.94974903, 0.05025097],
       [0.93130103, 0.06869897],
       [0.04842379, 0.95157621],
       [0.92793932, 0.07206068],
       [0.89578915, 0.10421085],
       [0.47813053, 0.52186947],
       [0.98095754, 0.01904246],
       [0.09482357, 0.90517643],
       [0.96452204, 0.03547796],
       [0.27092297, 0.72907703],
       [0.09234407, 0.90765593],
       [0.97335195, 0.02664805],
       [0.96062896, 0.03937104],
       [0.20567729, 0.79432271],
       [0.60539894, 0.39460106],
       [0.27329882, 0.72670118],
       [0.55547786, 0.44452214],
       [0.08598616, 0.91401384],
       [0.

In [12]:
yhat_test = f.predict(xtest)
yhat_test_prob = f.predict_proba(xtest)

In [13]:
yhat_test_prob

array([[3.15424553e-02, 9.68457545e-01],
       [7.47939083e-01, 2.52060917e-01],
       [7.12079712e-01, 2.87920288e-01],
       [2.52163121e-01, 7.47836879e-01],
       [1.22833532e-01, 8.77166468e-01],
       [9.54261018e-01, 4.57389821e-02],
       [2.04675587e-01, 7.95324413e-01],
       [1.65844766e-01, 8.34155234e-01],
       [8.62347750e-01, 1.37652250e-01],
       [1.68712746e-01, 8.31287254e-01],
       [9.89421150e-02, 9.01057885e-01],
       [9.00629069e-01, 9.93709314e-02],
       [8.85665260e-01, 1.14334740e-01],
       [1.10466987e-02, 9.88953301e-01],
       [1.42453724e-01, 8.57546276e-01],
       [8.37133123e-01, 1.62866877e-01],
       [9.87035182e-01, 1.29648179e-02],
       [8.31428546e-01, 1.68571454e-01],
       [4.26552728e-01, 5.73447272e-01],
       [9.76206928e-01, 2.37930719e-02],
       [5.01086274e-02, 9.49891373e-01],
       [8.29138047e-01, 1.70861953e-01],
       [5.06385447e-01, 4.93614553e-01],
       [1.66687116e-01, 8.33312884e-01],
       [9.151603

In [15]:
pd.crosstab(yhat_train,ytrain)

Species   0   1
row_0          
0        29   3
1         3  25

In [16]:
pd.crosstab(yhat_test,ytest) #test 총 40개중 30개는 잘 맞춤 (15+15), row값과 column값이 다르면, 잘 못맞춘다는 것을 의미 (7,3)처럼

Species   0   1
row_0          
0        15   7
1         3  15

In [19]:
#acc계산, xtrain, ytrain
f.score(xtrain,ytrain)

0.9

In [20]:
#xtest, ytest, test값이 train값보다 약간 나쁜것을 확인할 수 있다.
f.score(xtest,ytest)

0.75

# **logistic regression with StatsModels**

In [21]:
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [22]:
#통계적인 내용(통계모델에 관심 있을 경우 실행하면 된다.)
X = xtrain[['Petal.Length']]
X = sm.add_constant(X)
y = ytrain
f = sm.Logit(y,X)
r = f.fit()
r.summary()

# using a full model
X = xtrain
X = sm.add_constant(X)
y = ytrain
f = sm.Logit(y,X)
r = f.fit()
r.summary()

# training set
yhat_train_prob = r.predict(X)
yhat_train = (yhat_train_prob>0.5).astype(int)
pd.crosstab(yhat_train,ytrain)

# test set
yhat_test_prob = r.predict(sm.add_constant(xtest))
yhat_test = (yhat_test_prob>0.5).astype(int)
pd.crosstab(yhat_test,ytest)



Optimization terminated successfully.
         Current function value: 0.390325
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.229656
         Iterations 9


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


Species   0   1
row_0          
0        15   7
1         3  15